# .readthedocs.yaml
version: 2

# OS and Python environment used to build the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Install your project and dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

# Optional: build additional formats
formats:
  - pdf
  - epub

# Keep RTD environment clean between builds
build:
  jobs:
    pre_build:
      - pip install myst-parser pydata-sphinx-theme
